version: "3.9"
services:
  db:
    image: postgres
    container_name: pg-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=database
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - network
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
  kafka:
    image: apache/kafka
    ports:
      - 9092:9092
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    networks:
      - network
  web:
    build: ./client
    container_name: web
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/web
    command:
      - pnpm i
      - pnpm run build
      - pnpm run start
    depends_on:
      - api
    networks:
      - network
  api:
    build: ./server
    container_name: server
    ports:
      - 8000:8000
    volumes:
      - ./server:/usr/src/api
    command:
      - pnpm i
      - pnpm run build
      - pnpm run start
    depends_on:
      - db
      - redis
      - kafka
    networks:
      - network
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - api
networks:
  network:
